### ISSUE TITLE
./build.sh Release errors out with "ld: library not found for -lAFNetworking"

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/generikacc#33]
I do
```
1. Pod install
2. ./build.sh Release
```
and then I get the following error:

```ld: warning: directory not found for option '-L/Users/zdavatz/Documents/xcode/generikacc/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Generika/BuildProductsPath/Release-iphoneos/NTMonthYearPicker'
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **
```

**Comment by zdavatz** [comment]
If I build directly with Xcode (not from commandline) I get the following error:
<img width="869" alt="bildschirmfoto 2018-12-02 um 11 09 01" src="https://user-images.githubusercontent.com/4953/49338560-c210c500-f622-11e8-89f8-f1f7bb23315d.png">

**Comment by zdavatz** [comment]
this did not help: `rm -rf Pods/ Podfile.lock ; pod install`

**Comment by bettar** [comment]
I can do the pod install successfully, but those 5 libraries are not where Xcode thinks they should be. I'm still using the original git commit that "used to work".

**Comment by b123400** [comment]
I got it working by changing [`-project Generika.xcodeproj`](https://github.com/zdavatz/generikacc/blob/master/build.sh#L24) to `-workspace Generika.xcworkspace`, will be weird if it has been working...
But the script still fails, [here](https://github.com/zdavatz/generikacc/blob/master/build.sh#L65) it looks for `./exportOptions/store.plist` but that file doesn't exist.

**Comment by bettar** [comment]
Why is line 65 ending with \ ?
What's after that ?

**Comment by zdavatz** [comment]
ok, I may have the store.plist file
