### ISSUE TITLE
Square is not drawn around the EAN-13 barcode.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/generikacc#36]
See: 
https://files.slack.com/files-pri/T27F6280H-FEH6Q5NSG/file_from_ios.mp4

The square around the matrix code is correct.

**Comment by b123400** [comment]
Vision API gives me a line instead of an area, e.g. topRight is same as bottomRight. I think it's technically correct considering how a barcode is detected.

**Comment by b123400** [comment]
The API only provides 4 points (it might not be a rectangle)🤔

**Comment by b123400** [comment]
Maybe I can try to expend the line so it becomes a rectangle? But it would still in inaccurate

**Comment by zdavatz** [comment]
Vision API should be able to draw the rectangle correctly.

**Comment by zdavatz** [comment]
zbar was also able to draw a rectangle.

**Comment by b123400** [comment]
Um... I can try to expend the line to a square so it looks better

**Comment by zdavatz** [comment]
Maybe you can get some hints from here: https://github.com/googlesamples/ios-vision.git

**Comment by zdavatz** [comment]
Ok, let's close this and focus on #38
