### ISSUE TITLE
merge build.sh and testflight.sh

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/generikacc#49]
Das Script [build.sh](https://github.com/zdavatz/generikacc/blob/master/build.sh) und [testflight.sh](https://github.com/zdavatz/generikacc/blob/master/testflight.sh) müssen in ein build-script zusammengeführt werden. Für AmiKo-iOS klappt das sehr gut, siehe:

Mit dem Build Script muss 
* Pod install
* archchive
* export
* .ipa upload

stattfinden. Siehe das Build-Script von [iOS](https://github.com/zdavatz/AmiKo-iOS/blob/master/scripts/build.sh).

**Comment by zdavatz** [comment]
Das Script [build.sh](https://github.com/zdavatz/generikacc/blob/master/build.sh) und [testflight.sh](https://github.com/zdavatz/generikacc/blob/master/testflight.sh) müssen in ein build-script zusammengeführt werden. Für AmiKo-iOS klappt das sehr gut, siehe:

Mit dem Build Script muss 
* Pod install
* archchive
* export
* .ipa upload

stattfinden. Siehe das Build-Script von iOS.

**Comment by zdavatz** [comment]
https://github.com/zdavatz/AmiKo-iOS/blob/master/scripts/build.sh

**Comment by zdavatz** [comment]
bitte das build.sh in das `scripts` dir verschieben und auch store.plist in das Verzeichnis legen.

**Comment by zdavatz** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>compileBitcode</key>
        <true/>
        <key>method</key>
        <string>app-store</string>
        <key>teamID</key>
        <string>4B37356EGR</string>
        <key>uploadBitcode</key>
        <true/>
        <key>uploadSymbols</key>
        <true/>
</dict>
</plist>
```

**Comment by b123400** [comment]
Und `adhoc.plist`? Das Script benutzt `adhoc.plist` wenn es ist Release nicht.

**Comment by zdavatz** [comment]
Wir brauchen nur die `Release` option. Die anderen kannst Du weglassen. Somit brauchen wir `adhoc.plist` auch nicht.

**Comment by zdavatz** [comment]
Das Build-Script von [AmiKo-iOS](https://github.com/zdavatz/AmiKo-iOS/blob/master/scripts/build.sh) macht einfach einen .ipa upload zu iTunesConnect, von gibt es dann einen Testflight Release.

**Comment by zdavatz** [comment]
ich will wirklich nur `$ ./build.sh` ausführen müssen, ohne weitere Optionen.

**Comment by b123400** [comment]
Ok

**Comment by zdavatz** [comment]
Super, Danke!
